[package]
name = "llmtool"
description = "The macro for the llmtoolbox crate"
version = "0.0.1"
edition = "2021"
repository = "https://github.com/mcmah309/llmtoolbox"
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
syn = "2"
quote = "1"
proc-macro2 = "1"
regex = "1"